-- MySQL Script generated by MySQL Workbench
-- Sun Apr 15 18:22:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Type` (
  `idType` INT NOT NULL,
  `typeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`),
  UNIQUE INDEX `typeName_UNIQUE` (`typeName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Object` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Object` (
  `idObject` INT NOT NULL,
  `type` INT NOT NULL,
  `height` INT NULL,
  `width` INT NULL,
  `posX` INT NULL,
  `posY` INT NULL,
  PRIMARY KEY (`idObject`),
  CONSTRAINT `type`
    FOREIGN KEY (`idObject`)
    REFERENCES `mydb`.`Type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HousePlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HousePlan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HousePlan` (
  `idHousePlan` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHousePlan`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Composition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Composition` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Composition` (
  `idComposition` INT NOT NULL,
  `object` INT NOT NULL,
  `plan` INT NOT NULL,
  PRIMARY KEY (`idComposition`),
  INDEX `plan_idx` (`plan` ASC),
  INDEX `object_idx` (`object` ASC),
  CONSTRAINT `object`
    FOREIGN KEY (`object`)
    REFERENCES `mydb`.`Object` (`idObject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plan`
    FOREIGN KEY (`plan`)
    REFERENCES `mydb`.`HousePlan` (`idHousePlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
